package com.pockettechnician.app.ui.screens

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.Forum
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.Icon
import androidx.compose.material3.ListItem
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier

private data class MockConversation(val name: String, val subtitle: String)

private val mockConversations = listOf(
    MockConversation("Office laptop has no internet", "Today · 14 messages"),
    MockConversation("Printer not detected after update", "Yesterday · 9 messages"),
    MockConversation("Wi-Fi keeps dropping in meeting room", "Mon · 22 messages"),
)

@Composable
fun ConversationsScreen() {
    ScreenContainer(title = "Conversations") {
        Button(onClick = { /* start a new conversation */ }, modifier = Modifier.fillMaxWidth()) {
            Icon(Icons.Filled.Add, contentDescription = null)
            Text("  New Conversation")
        }

        mockConversations.forEach { conversation ->
            Card(modifier = Modifier.fillMaxWidth()) {
                ListItem(
                    headlineContent = { Text(conversation.name) },
                    supportingContent = {
                        Text(
                            conversation.subtitle,
                            color = MaterialTheme.colorScheme.onSurfaceVariant,
                        )
                    },
                    leadingContent = { Icon(Icons.Filled.Forum, contentDescription = null) },
                )
            }
        }

        Column {
            Text(
                "Tap a conversation to load it into the Chat tab. Names are " +
                    "generated by the model in the background.",
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
            )
        }
    }
}
