package com.pockettechnician.app.ui.screens

import android.text.format.DateUtils
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material.icons.filled.Forum
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.ListItem
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.lifecycle.viewmodel.compose.viewModel
import com.pockettechnician.app.PocketTechnicianApplication
import com.pockettechnician.app.data.chat.ConversationSummary
import com.pockettechnician.app.data.chat.displayTitle
import com.pockettechnician.app.ui.conversations.ConversationsViewModel

@Composable
fun ConversationsScreen(onOpenChat: () -> Unit) {
    val application = LocalContext.current.applicationContext as PocketTechnicianApplication
    val viewModel: ConversationsViewModel =
        viewModel(factory = ConversationsViewModel.Factory(application))
    val conversations by viewModel.conversations.collectAsState()

    ScreenContainer(title = "Conversations") {
        Button(
            onClick = { viewModel.createNew(onCreated = onOpenChat) },
            modifier = Modifier.fillMaxWidth(),
        ) {
            Icon(Icons.Filled.Add, contentDescription = null)
            Text("  New Conversation")
        }

        if (conversations.isEmpty()) {
            Text(
                "No conversations yet. Start one here or just type on the Chat tab.",
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
            )
        }

        conversations.forEach { conversation ->
            ConversationCard(
                conversation = conversation,
                onOpen = { viewModel.open(conversation.id, onOpened = onOpenChat) },
                onDelete = { viewModel.delete(conversation.id) },
            )
        }

        Text(
            "Tap a conversation to load it into the Chat tab. Names are " +
                "generated by the model in the background.",
            style = MaterialTheme.typography.bodySmall,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
        )
    }
}

@Composable
private fun ConversationCard(
    conversation: ConversationSummary,
    onOpen: () -> Unit,
    onDelete: () -> Unit,
) {
    Card(
        modifier = Modifier
            .fillMaxWidth()
            .clickable(onClick = onOpen),
    ) {
        ListItem(
            headlineContent = { Text(conversation.displayTitle) },
            supportingContent = {
                Text(
                    conversation.subtitle(),
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                )
            },
            leadingContent = { Icon(Icons.Filled.Forum, contentDescription = null) },
            trailingContent = {
                IconButton(onClick = onDelete) {
                    Icon(Icons.Filled.Delete, contentDescription = "Delete conversation")
                }
            },
        )
    }
}

private fun ConversationSummary.subtitle(): String {
    val age = DateUtils.getRelativeTimeSpanString(
        updatedAtEpochMillis,
        System.currentTimeMillis(),
        DateUtils.MINUTE_IN_MILLIS,
    )
    val count = if (messageCount == 1) "1 message" else "$messageCount messages"
    return "$age · $count"
}
